### ISSUE TITLE
Output directory name same as file name?

### ISSUE THREAD

**Issue by ClaudeJanssenPro** [cmmodtools/modtools#1]
Hello,

would that possible to have a parameter so that the output directory name is the brz's name?

Thank you for your tools, I love the command line parameters.

**Comment by cmmodtools** [comment]
Hi Claude,
Thank you for you kind feedback.

The functionality you want is absolutely available. I am a strong believer in the UNIX philosophy, so to do what you want you will need to leverage some standard UNIX command line tools.

For example, to extract all the Normandy BRZ files into separate output directories you could use the following command:

`DIR="/Applications/CM Battle for Normandy"`
`find $DIR -type f -name "*.brz" -exec sh -c 'rezexplode -o $(basename -s .brz {}) {}' \;`

If you would prefer a tool to do it automatically then take a look at the `rezstrip.sh` shell script. Lines 38-41 in that file unpack each command line parameter into a separate output directory. All you need to do to create the tool is delete all lines after that. For example, to create a `rezsepexplode.sh` tool:

`sed '42,$d' rezstrip.sh > rezsepexplode.sh && chmod a+x rezsepexplode.sh`

Then to extract all the Normandy v3.x BRZ files simply run:

`./rezsepexplode.sh /Applications/CM\ Battle\ for\ Normandy/CM\ Battle\ for\ Normandy.app/Contents/Resources/Data/normandy\ v3*`

**Comment by ClaudeJanssenPro** [comment]
Thanks a lot Michal. I'm on Windows and that shouldn't be an issue. You made my life easier! ;)
